FROM alpine:3.7
#RUN yum install supervisor -y
#RUN apk update && apk add --no-cache supervisor
#RUN apk add --no-cache supervisor
RUN apk add --no-cache python
#COPY /files/supervisord.conf /etc/supervisord.conf
#CMD ["/usr/bin/supervisord"]
#RUN apk add --no-cache mysql-client
#ENTRYPOINT ["mysql"]
